# app/config/security.yml
security:
    # ...
    encoders:
        App\Entity\User:
            algorithm: plaintext

    providers:
        our_db_provider:
            entity:
                class: App\Entity\User
                property: username    

    firewalls:
        default:
            anonymous: ~
            http_basic: ~
            provider: our_db_provider
            form_login:
                login_path: /login
                check_path: /login_check